###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "titulo": "Los 8 habitos de las personas netamente efectivas",
    "autor": "Perez Carrazco",
    "edicion": 3
}

###
DELETE  http://localhost:9000/api/3 HTTP/1.1

###
PUT http://localhost:9000/api/1 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Los 8 habitos de Actualizar",
    "autor": "Nuetro Actual",
    "edicion": 8
}